sudo: required
services:
        - docker

before_script:
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - curl https://cli-assets.heroku.com/install.sh | sh  #install heroku
        - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com 

script:
        - docker build -t calvinpuram/getIdea .
        - docker tag calvinpuram/getidea registry.heroku.com/$HEROKU_APP/web 
          
deploy:   
        provider: script
        script: 
               docker push calvinpuram/getidea;
               docker push registry.heroku.com/$HEROKU_APP/web;
               heroku container:release web --app $HEROKU_APP
        on:
          branch: main