version: "3.7"
services:
  app:
    container_name: app
    restart: always
    build: .
    environment:
      - PORT=4000
    ports:
      - "4000:4000"
    links:
      - mongo
      
  db:
    container_name: db
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: node-app
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    



volumes:
  mongo_data: {}
  mongo_config: {}